when:
  - event: pull_request
  - event: push
    branch: [feature/*, preview, main]

steps:
  - name: validate
    image: node@sha256:dd9d21971ec4395903fa6143c2b9267d048ae01ca6d3ea96f16cb30df6187d94
    commands:
      - npm install --global --no-audit --no-fund pnpm@12.4.1
      - pnpm install --frozen-lockfile
      - pnpm contract:verify
      - pnpm lint
      - pnpm typecheck
      - pnpm test
